# Generated by Django 2.2.5 on 2020-04-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20200406_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='room',
            field=models.ManyToManyField(blank=True, related_name='lists', to='rooms.Room'),
        ),
    ]
